export interface ScenarioCheckpoint {
  headline: string;
  detail: string;
}

export interface OfficialLink {
  label: string;
  url: string;
}

export interface Scenario {
  id: string;
  title: string;
  formatLabel: string;
  audienceLabel: string;
  triggerQuestion: string;
  summary: string;
  whyThisMatters: string;
  commonMistake: string;
  nextMove: string;
  tags: string[];
  filters: string[];
  checkpoints: ScenarioCheckpoint[];
  officialLinks: OfficialLink[];
}

export const SCENARIO_FILTERS = [
  { id: "all", label: "All scenarios" },
  { id: "forms", label: "Forms" },
  { id: "platforms", label: "Platforms" },
  { id: "payouts", label: "Payouts" },
  { id: "records", label: "Records" },
  { id: "cross-border", label: "Cross-border" },
  { id: "year-round", label: "Year-round" },
  { id: "self-employed", label: "Self-employed" },
  { id: "deductions", label: "Deductions" },
];

export const SCENARIOS: Scenario[] = [
  {
    id: "youtube-us-tax-info",
    title: "YouTube creator outside the U.S. gets a tax form prompt",
    formatLabel: "Platform scenario",
    audienceLabel: "Non-U.S. YouTubers and AdSense creators",
    triggerQuestion: "Google is asking for U.S. tax info even though I do not live in the U.S. What am I actually supposed to do?",
    summary: "This is usually a platform-tax workflow problem before it becomes a filing problem. The right move is to identify which profile, form, and treaty path Google is asking for before guessing through the prompt.",
    whyThisMatters: "A rushed platform tax submission can create avoidable withholding, rejected forms, or a documentation mess later.",
    commonMistake: "Treating the YouTube prompt like a generic settings screen instead of a tax interview tied to specific IRS forms and year-end reporting.",
    nextMove: "Start with the YouTube help article and confirm which individual or entity tax form path applies before submitting anything.",
    tags: ["Creators", "Platforms", "Cross-border"],
    filters: ["platforms", "forms", "cross-border"],
    checkpoints: [
      { headline: "Confirm which Google payments profile is involved", detail: "The request is tied to the revenue-generating account and its legal profile, not just your public channel identity." },
      { headline: "Check whether Google is asking for W-9, W-8BEN, or another path", detail: "The correct tax form depends on whether the payee is a U.S. person, a non-U.S. individual, or an entity using a different IRS form workflow." },
      { headline: "Review treaty or withholding implications before submitting", detail: "If a treaty benefit could apply, you want the official instructions in front of you before accepting the default withholding result." },
      { headline: "Know which year-end form may arrive later", detail: "The submission step and the year-end reporting step are related but different. You may later need a 1042-S or another U.S. tax form for records." },
    ],
    officialLinks: [
      { label: "YouTube Help: submitting U.S. tax info", url: "https://support.google.com/youtube/answer/10390801" },
      { label: "YouTube Help: request year-end U.S. tax forms", url: "https://support.google.com/youtube/troubleshooter/7542675" },
      { label: "IRS Form W-8BEN", url: "https://www.irs.gov/forms-pubs/about-form-w-8-ben" },
      { label: "IRS Form 1042-S", url: "https://www.irs.gov/forms-pubs/about-form-1042-s" },
    ],
  },
  {
    id: "brand-deal-paperwork",
    title: "A sponsor asks for a W-9 before paying a creator",
    formatLabel: "Paperwork scenario",
    audienceLabel: "Creators landing brand deals and freelance campaigns",
    triggerQuestion: "Why is the brand asking for a W-9 now, and how is that different from whatever tax form shows up later?",
    summary: "This is the most common creator paperwork mix-up. The W-9 is usually setup information for the payer, while year-end reporting and your own recordkeeping happen on different clocks.",
    whyThisMatters: "Getting the setup form wrong can trigger backup withholding, corrected reporting, or a long cleanup loop when the payer prepares the year-end form.",
    commonMistake: "Assuming the W-9 is the final tax form or waiting for a platform or brand to reconstruct your income history for you.",
    nextMove: "Verify the W-9 and the likely year-end reporting form, then keep your own payment ledger instead of relying on the payer to explain your taxes.",
    tags: ["Creators", "Forms", "Payouts"],
    filters: ["forms", "payouts"],
    checkpoints: [
      { headline: "Treat the W-9 as a setup form", detail: "The payer is usually collecting your legal name and TIN so they can report payments correctly if a reporting form is required later." },
      { headline: "Separate the setup step from the reporting step", detail: "The W-9 does not calculate your tax. A later 1099-NEC or 1099-K may report payment activity depending on the workflow." },
      { headline: "Match names and taxpayer information exactly", detail: "Accuracy matters at the front door because mismatches can create corrected forms, withholding issues, or payout delays." },
      { headline: "Maintain your own gross receipts log", detail: "Even when a payer reports later, your own records should still show each invoice, payment date, and business purpose." },
    ],
    officialLinks: [
      { label: "IRS Form W-9", url: "https://www.irs.gov/forms-pubs/about-form-w-9" },
      { label: "IRS Form 1099-NEC", url: "https://www.irs.gov/forms-pubs/about-form-1099-nec" },
      { label: "IRS Form 1099-K FAQs", url: "https://www.irs.gov/newsroom/form-1099-k-faqs" },
    ],
  },
  {
    id: "patreon-gross-vs-net",
    title: "Platform payout says one number, tax reporting may show another",
    formatLabel: "Payout scenario",
    audienceLabel: "Patreon and multi-platform subscription creators",
    triggerQuestion: "Patreon fees came out of the payout, so why might the tax form still reflect a bigger gross number?",
    summary: "Platform creators often focus on cash received, but some tax reporting workflows emphasize gross payments before fees, refunds, or platform deductions are netted down.",
    whyThisMatters: "If you only track the bank deposit amount, your books can stop matching platform dashboards and year-end forms.",
    commonMistake: "Using the bank deposit as the only tax record and forgetting that platform fees and gross receipts may need separate tracking.",
    nextMove: "Reconcile platform gross payments, fees, refunds, and net payouts in one ledger before filing season forces you to backfill it.",
    tags: ["Creators", "Platforms", "Records"],
    filters: ["platforms", "payouts", "records"],
    checkpoints: [
      { headline: "Start from the platform transaction report", detail: "Look for gross receipts, fees, taxes collected by the platform, chargebacks, and net payout timing in the dashboard export." },
      { headline: "Compare that report with 1099-K guidance", detail: "The reporting form can focus on gross payment amounts for goods or services rather than the smaller net number that hit your bank." },
      { headline: "Track fees as expenses instead of invisible shrinkage", detail: "When fees disappear into the net payout, you still need a record showing what was earned and what was paid out as expense." },
      { headline: "Document unusual items early", detail: "Refunds, failed charges, and cross-platform payouts are easier to explain when the reconciliation was done during the year instead of at filing time." },
    ],
    officialLinks: [
      { label: "Patreon creator tax FAQ", url: "https://support.patreon.com/hc/en-us/articles/207477063-Taxes-101-How-do-taxes-work-on-Patreon-" },
      { label: "IRS Form 1099-K FAQs", url: "https://www.irs.gov/newsroom/form-1099-k-faqs" },
      { label: "IRS self-employed tax center", url: "https://www.irs.gov/businesses/small-businesses-self-employed/self-employed-individuals-tax-center" },
    ],
  },
  {
    id: "quarterly-cashflow",
    title: "A creator starts earning mid-year and nobody is withholding",
    formatLabel: "Cash-flow scenario",
    audienceLabel: "First-year creators, freelancers, and side-hustlers",
    triggerQuestion: "If no one is withholding taxes from my creator income, do I really need to think about tax before April?",
    summary: "This is the classic creator tax shock. The income looks spendable, but the tax system still expects a pay-as-you-go mindset once enough untaxed income starts landing.",
    whyThisMatters: "Quarterly tax habits reduce underpayment risk and prevent the year-end scramble that turns every payout into a surprise.",
    commonMistake: "Waiting until filing season to learn estimated taxes exist, then trying to reverse-engineer a year of income and cash spending.",
    nextMove: "Open the estimated tax guidance now, then create a same-day tax reserve habit for every untaxed payout.",
    tags: ["Creators", "Year-round", "Self-employed"],
    filters: ["year-round", "payouts"],
    checkpoints: [
      { headline: "Identify which payouts are landing without withholding", detail: "Creator platforms, sponsorships, and freelance invoices often show up as fully spendable cash even though tax still sits inside the payment." },
      { headline: "Check estimated tax guidance before the next quarter turns over", detail: "The relevant question is not whether you feel ready to file. It is whether the pay-as-you-go system expects a payment cycle earlier." },
      { headline: "Create a tax reserve rule", detail: "A separate tax bucket and a repeatable transfer habit are usually more useful than trying to perfectly forecast the final return all at once." },
      { headline: "Keep the records that support the cash story", detail: "Quarterly planning gets much easier when income and expenses are logged continuously instead of rebuilt from memory." },
    ],
    officialLinks: [
      { label: "IRS Form 1040-ES", url: "https://www.irs.gov/forms-pubs/about-form-1040-es" },
      { label: "IRS self-employed tax center", url: "https://www.irs.gov/businesses/small-businesses-self-employed/self-employed-individuals-tax-center" },
      { label: "IRS filing and paying business taxes", url: "https://www.irs.gov/businesses/small-businesses-self-employed/filing-and-paying-your-business-taxes" },
    ],
  },
  {
    id: "gear-writeoff-boundaries",
    title: "Creator gear, software, and home setups are not automatic write-offs",
    formatLabel: "Deduction scenario",
    audienceLabel: "Creators buying cameras, software, lighting, and home office gear",
    triggerQuestion: "If I use it to create content or it appears on camera, can I just deduct it?",
    summary: "Creator work makes personal and business use blur together fast. The safest starting point is to separate business purpose, exclusive-use rules, and documentation before assuming the write-off exists.",
    whyThisMatters: "Creators often mix personal lifestyle purchases with genuine business tools. The tax answer turns on facts and records, not on how expensive the purchase felt.",
    commonMistake: "Assuming every camera, trip, phone, room, or software subscription becomes deductible the second content is involved.",
    nextMove: "Start by documenting business use, then verify ordinary and necessary expense treatment and home office eligibility before claiming anything.",
    tags: ["Creators", "Records", "Deductions"],
    filters: ["records", "year-round"],
    checkpoints: [
      { headline: "Ask whether the expense has a clear business purpose", detail: "The more mixed the personal and business use story is, the more important contemporaneous documentation becomes." },
      { headline: "Separate equipment from workspace rules", detail: "A camera purchase and a home office claim rely on different analyses. A creator can have one without automatically qualifying for the other." },
      { headline: "Check exclusive-use rules before claiming home office", detail: "Working from home or filming in a room is not the same thing as meeting the business-use standard for the deduction." },
      { headline: "Keep invoices, usage notes, and records now", detail: "The tax story is stronger when the documentation existed when you made the purchase, not after you decided you wanted the deduction." },
    ],
    officialLinks: [
      { label: "IRS Publication 535", url: "https://www.irs.gov/forms-pubs/about-publication-535" },
      { label: "IRS simplified home office method", url: "https://www.irs.gov/businesses/small-businesses-self-employed/simplified-option-for-home-office-deduction" },
      { label: "IRS Publication 587", url: "https://www.irs.gov/publications/p587" },
    ],
  },
  {
    id: "crypto-staking-income",
    title: "Crypto staking rewards are taxable income when received",
    formatLabel: "Income scenario",
    audienceLabel: "Crypto holders earning staking, yield, and validator rewards",
    triggerQuestion: "I earned staking rewards from my crypto holdings. Are those taxable even if I never sold or converted anything?",
    summary: "Staking rewards are treated as ordinary income at fair market value when you gain dominion and control over them. This applies regardless of whether you later sell, swap, or hold the tokens.",
    whyThisMatters: "Crypto staking can generate a continuous stream of taxable events throughout the year. Ignoring them creates an income gap the IRS can detect through exchange reporting and blockchain analytics.",
    commonMistake: "Treating staking rewards like unrealized capital gains and assuming no tax is due until the tokens are sold or converted to fiat currency.",
    nextMove: "Start tracking the fair market value of each staking reward at the moment it is received, and set aside estimated tax on the income as it accrues.",
    tags: ["Crypto", "Self-employed", "Records"],
    filters: ["self-employed", "records"],
    checkpoints: [
      { headline: "Staking rewards are ordinary income at receipt", detail: "The IRS treats staking rewards as taxable income at the fair market value on the date and time you gain dominion and control over the tokens." },
      { headline: "Track the cost basis of each reward separately", detail: "Each staking reward becomes a new tax lot. The fair market value at receipt is your cost basis for calculating gain or loss if you later sell or exchange the tokens." },
      { headline: "Exchange 1099s may not capture everything", detail: "Not all staking platforms issue 1099 forms, and those that do may not match your actual reward timing. Self-tracking with a crypto tax tool is essential." },
      { headline: "Estimated tax payments may apply", detail: "If staking income is substantial and no one is withholding, quarterly estimated tax payments may be required to avoid underpayment penalties." },
    ],
    officialLinks: [
      { label: "IRS Revenue Ruling 2023-14 (staking rewards)", url: "https://www.irs.gov/individuals/international-taxpayers/frequently-asked-questions-on-virtual-currency-transactions" },
      { label: "IRS Notice 2014-21 (virtual currency guidance)", url: "https://www.irs.gov/irb/2014-16_IRB#NOT-2014-21" },
      { label: "IRS crypto FAQ", url: "https://www.irs.gov/individuals/international-taxpayers/frequently-asked-questions-on-virtual-currency-transactions" },
    ],
  },
  {
    id: "foreign-bank-fbar",
    title: "Foreign bank accounts over $10K require FBAR reporting",
    formatLabel: "Compliance scenario",
    audienceLabel: "U.S. persons with bank or financial accounts outside the U.S.",
    triggerQuestion: "I have bank accounts abroad. Do I need to report them to the IRS or another agency even if I already pay taxes on the income?",
    summary: "If the aggregate value of all foreign financial accounts exceeds $10,000 at any point during the year, you must file FinCEN Form 114 (FBAR). This is a separate obligation from your income tax return.",
    whyThisMatters: "FBAR penalties are among the harshest in the tax system. Willful violations can result in penalties up to the greater of $100,000 or 50% of the account balance per violation.",
    commonMistake: "Confusing FBAR with FATCA Form 8938. They are separate filings with different thresholds, different due dates, and different enforcement agencies.",
    nextMove: "Check the maximum aggregate balance of all foreign accounts during the year. If it exceeded $10,000, file FinCEN Form 114 electronically through the BSA E-Filing system by April 15 (automatic extension to October 15).",
    tags: ["Cross-border", "Forms", "Compliance"],
    filters: ["cross-border", "forms"],
    checkpoints: [
      { headline: "The $10K threshold is aggregate across all foreign accounts", detail: "Add up the maximum balances of every foreign account you held during the year. If the total exceeded $10,000 at any point, you must file." },
      { headline: "FBAR is filed with FinCEN, not the IRS", detail: "The Report of Foreign Bank and Financial Accounts is filed electronically through the BSA E-Filing System, not with your tax return." },
      { headline: "FBAR and FATCA Form 8938 are not the same", detail: "Form 8938 has higher thresholds and is filed with your tax return. You may need to file both, one, or neither depending on your account values." },
      { headline: "Penalties for non-filing are severe", detail: "Non-willful penalties can reach $10,000 per violation. Willful violations face much steeper penalties and potential criminal prosecution." },
    ],
    officialLinks: [
      { label: "FinCEN FBAR filing instructions", url: "https://www.fincen.gov/report-foreign-bank-and-financial-accounts" },
      { label: "IRS FBAR reference guide", url: "https://www.irs.gov/businesses/small-businesses-self-employed/report-of-foreign-bank-and-financial-accounts-fbar" },
      { label: "IRS Form 8938 (FATCA)", url: "https://www.irs.gov/forms-pubs/about-form-8938" },
    ],
  },
  {
    id: "1099-vs-w2-misclassification",
    title: "Worker misclassified as 1099 contractor instead of W-2 employee",
    formatLabel: "Classification scenario",
    audienceLabel: "Freelancers, gig workers, and anyone receiving a 1099 who may be an employee",
    triggerQuestion: "I work set hours, use company equipment, and follow their processes, but I get a 1099 instead of a W-2. Is this right?",
    summary: "Worker classification determines who pays employment taxes, what deductions are available, and what protections apply. Misclassification is common and has significant tax and legal consequences for both the worker and the business.",
    whyThisMatters: "A misclassified worker pays both halves of self-employment tax, loses unemployment and workers compensation protections, and may miss employer-provided benefits they should have received.",
    commonMistake: "Assuming the company gets to choose how to classify you. Classification depends on the actual working relationship, not on what the contract says or what the company prefers.",
    nextMove: "Review the IRS behavioral, financial, and relationship factors. If misclassification seems likely, Form SS-8 lets you request an IRS determination.",
    tags: ["Self-employed", "Forms", "Employment"],
    filters: ["self-employed", "forms"],
    checkpoints: [
      { headline: "Apply the IRS three-factor test", detail: "Behavioral control, financial control, and relationship type determine classification. No single factor is decisive, but the overall pattern matters." },
      { headline: "Understand the tax impact of 1099 vs W-2", detail: "1099 workers pay self-employment tax (15.3%) on net earnings. W-2 employees split FICA with the employer and have taxes withheld automatically." },
      { headline: "Form SS-8 requests an IRS determination", detail: "Either the worker or the business can file Form SS-8 to ask the IRS to rule on classification. The process takes time but creates an official determination." },
      { headline: "State rules may differ from federal rules", detail: "Many states use stricter tests like the ABC test. You may be an employee under state law even if the federal analysis is less clear." },
    ],
    officialLinks: [
      { label: "IRS worker classification overview", url: "https://www.irs.gov/businesses/small-businesses-self-employed/independent-contractor-self-employed-or-employee" },
      { label: "IRS Form SS-8", url: "https://www.irs.gov/forms-pubs/about-form-ss-8" },
      { label: "IRS Publication 15-A (employer supplement)", url: "https://www.irs.gov/publications/p15a" },
    ],
  },
  {
    id: "state-nexus-sales-tax",
    title: "Online sellers may owe sales tax in states where they have nexus",
    formatLabel: "Compliance scenario",
    audienceLabel: "E-commerce sellers, Shopify merchants, and online service providers",
    triggerQuestion: "I sell online from one state. Do I really need to collect and remit sales tax in other states where my customers live?",
    summary: "After the 2018 South Dakota v. Wayfair decision, states can require remote sellers to collect sales tax once they exceed economic nexus thresholds (typically $100,000 in sales or 200 transactions in that state). Physical presence is no longer required.",
    whyThisMatters: "Sales tax liability accumulates quickly across states. Sellers who ignore nexus obligations face back taxes, penalties, and interest from multiple state tax authorities simultaneously.",
    commonMistake: "Assuming sales tax only applies where the business is physically located, or that marketplace facilitator rules cover all sales channels.",
    nextMove: "Track sales volume by state, check each state's nexus threshold, and register for sales tax permits in states where you have crossed the threshold.",
    tags: ["E-commerce", "Records", "Year-round"],
    filters: ["records", "year-round"],
    checkpoints: [
      { headline: "Know your economic nexus thresholds by state", detail: "Most states set the threshold at $100,000 in sales or 200 transactions. Some use only a dollar threshold. Thresholds are measured on a calendar-year or trailing-12-month basis." },
      { headline: "Marketplace facilitator laws shift some obligations", detail: "Amazon, eBay, Etsy, and similar platforms collect and remit sales tax on your behalf in most states. But direct website sales and other channels remain your responsibility." },
      { headline: "Register before collecting", detail: "Collecting sales tax without a valid permit is illegal in most states. Register for a sales tax permit in each state where you have nexus before you start collecting." },
      { headline: "Taxability rules vary by state and product type", detail: "Some states exempt clothing, food, or digital goods. What is taxable in one state may be exempt in another. Product classification matters." },
    ],
    officialLinks: [
      { label: "IRS state and local tax guidance", url: "https://www.irs.gov/businesses/small-businesses-self-employed/state-government-websites" },
      { label: "Streamlined Sales Tax project", url: "https://www.streamlinedsalestax.org" },
      { label: "South Dakota v. Wayfair (Supreme Court)", url: "https://www.supremecourt.gov/opinions/17pdf/17-494_j4el.pdf" },
    ],
  },
  {
    id: "international-freelancer-tax-treaty",
    title: "Freelancer in a treaty country may reduce U.S. withholding",
    formatLabel: "Treaty scenario",
    audienceLabel: "Non-U.S. freelancers earning income from U.S. clients or platforms",
    triggerQuestion: "I am a freelancer living abroad and a U.S. company is withholding 30% from my payments. Can I reduce this using a tax treaty?",
    summary: "Many U.S. tax treaties provide reduced withholding rates or exemptions for independent personal services income. Claiming treaty benefits requires the correct W-8 form and specific treaty article citations.",
    whyThisMatters: "Without treaty benefits, non-resident aliens face 30% withholding on most U.S.-source income. A properly filed treaty claim can reduce this to 0-15% depending on the income type and treaty.",
    commonMistake: "Filing a W-8BEN without specifying the treaty article, or assuming the treaty applies to all income types rather than checking which specific categories are covered.",
    nextMove: "Identify whether your country has a tax treaty with the U.S., find the relevant article for independent services or business profits, and complete Form W-8BEN (individual) or W-8BEN-E (entity) with the treaty claim.",
    tags: ["Cross-border", "Forms", "Freelancers"],
    filters: ["cross-border", "forms"],
    checkpoints: [
      { headline: "Check if your country has a U.S. tax treaty", detail: "Not all countries have treaties with the U.S. Even among treaty countries, the specific provisions for freelance or services income vary significantly." },
      { headline: "Identify the correct treaty article", detail: "Independent personal services typically fall under the Business Profits article (often Article 7) or the Independent Personal Services article. The article determines the exemption scope." },
      { headline: "Use the right W-8 form with treaty claims", detail: "Individuals use W-8BEN with Part III completed for treaty benefits. Entities use W-8BEN-E. Both require a valid foreign tax identification number." },
      { headline: "Understand the limitation on benefits clause", detail: "Most modern U.S. treaties include a Limitation on Benefits article that requires the treaty claimant to meet specific ownership, income, or active trade tests." },
    ],
    officialLinks: [
      { label: "IRS tax treaty tables", url: "https://www.irs.gov/individuals/international-taxpayers/tax-treaty-tables" },
      { label: "IRS Form W-8BEN instructions", url: "https://www.irs.gov/forms-pubs/about-form-w-8-ben" },
      { label: "IRS Publication 901 (tax treaties)", url: "https://www.irs.gov/forms-pubs/about-publication-901" },
    ],
  },
  {
    id: "llc-vs-s-corp-election",
    title: "S-Corp election can reduce self-employment tax for profitable LLCs",
    formatLabel: "Entity scenario",
    audienceLabel: "LLC owners earning consistent profits above reasonable salary levels",
    triggerQuestion: "My single-member LLC is profitable. Should I elect S-Corp status to save on self-employment tax?",
    summary: "An S-Corp election lets an LLC owner split income between a reasonable salary (subject to FICA) and distributions (not subject to FICA). This can save thousands in self-employment tax, but only when income is high enough to justify the added complexity and payroll costs.",
    whyThisMatters: "Self-employment tax is 15.3% on the first $168,600 (2024) of net earnings. For a profitable LLC, reducing the amount subject to this tax through an S-Corp election can produce meaningful savings.",
    commonMistake: "Electing S-Corp too early when income is low, setting an unreasonably low salary to maximize distributions, or ignoring the additional payroll and filing costs that come with the election.",
    nextMove: "Calculate whether the self-employment tax savings exceed the costs of running payroll and filing Form 1120-S. The breakeven point is typically around $50,000-$80,000 in annual net profit.",
    tags: ["Self-employed", "Forms", "Year-round"],
    filters: ["forms", "year-round"],
    checkpoints: [
      { headline: "Understand how the savings work", detail: "Without S-Corp status, all LLC net income is subject to self-employment tax. With S-Corp status, only the reasonable salary portion is subject to FICA taxes." },
      { headline: "The reasonable salary requirement is real", detail: "The IRS requires S-Corp owner-employees to pay themselves a reasonable salary before taking distributions. Setting salary too low invites IRS scrutiny and reclassification." },
      { headline: "Factor in the added costs", detail: "S-Corp election requires Form 1120-S filing, quarterly payroll processing, W-2 issuance, and potentially higher accounting fees. These costs reduce the net benefit." },
      { headline: "File Form 2553 by the deadline", detail: "The S-Corp election must be filed within 75 days of the start of the tax year, or anytime in the prior tax year. Late elections require reasonable cause relief." },
    ],
    officialLinks: [
      { label: "IRS Form 2553 (S-Corp election)", url: "https://www.irs.gov/forms-pubs/about-form-2553" },
      { label: "IRS S-Corporation overview", url: "https://www.irs.gov/businesses/small-businesses-self-employed/s-corporations" },
      { label: "IRS Form 1120-S", url: "https://www.irs.gov/forms-pubs/about-form-1120-s" },
    ],
  },
  {
    id: "digital-nomad-tax-residency",
    title: "Working remotely from multiple countries creates complex tax residency",
    formatLabel: "Residency scenario",
    audienceLabel: "Digital nomads, remote workers, and location-independent professionals",
    triggerQuestion: "I work online while traveling between countries. Where do I actually owe taxes, and how do I avoid being taxed by multiple jurisdictions?",
    summary: "Tax residency is determined by each country's own rules (often based on physical presence, domicile, or center of vital interests). Working from multiple countries can trigger tax obligations in several jurisdictions simultaneously without careful planning.",
    whyThisMatters: "Being tax resident in multiple countries means potentially filing returns and paying taxes in each one. Double taxation treaties can help, but only if you know which countries claim you as a resident and plan accordingly.",
    commonMistake: "Assuming that being a digital nomad means paying taxes nowhere, or that short stays in a country cannot create tax obligations or permanent establishment risk.",
    nextMove: "Track your physical presence in each country carefully, research the tax residency rules for every country where you spend significant time, and confirm whether treaty tie-breaker rules can resolve dual residency.",
    tags: ["Cross-border", "Records", "Digital nomads"],
    filters: ["cross-border", "records"],
    checkpoints: [
      { headline: "Physical presence thresholds vary by country", detail: "Many countries trigger tax residency at 183 days, but some use shorter periods, rolling averages, or non-presence-based tests like domicile or center of vital interests." },
      { headline: "Permanent establishment risk for your business", detail: "Working from a country for your own business can create a taxable permanent establishment there, even if you do not intend to set up operations." },
      { headline: "Tax treaties include tie-breaker rules", detail: "When two countries both claim you as a tax resident, the treaty tie-breaker article resolves it based on permanent home, center of vital interests, habitual abode, and nationality." },
      { headline: "Keep a detailed travel log", detail: "A day-by-day record of which country you were in is essential for proving residency status to any tax authority that asks. Include flight records, accommodation receipts, and entry stamps." },
    ],
    officialLinks: [
      { label: "IRS tax residency for aliens", url: "https://www.irs.gov/individuals/international-taxpayers/determining-alien-tax-status" },
      { label: "IRS substantial presence test", url: "https://www.irs.gov/individuals/international-taxpayers/substantial-presence-test" },
      { label: "OECD model tax convention (Article 4)", url: "https://www.oecd.org/tax/treaties/model-tax-convention-on-income-and-on-capital-condensed-version-20745419.htm" },
    ],
  },
  {
    id: "amazon-fba-seller-tax",
    title: "FBA sellers face inventory nexus, sales tax, and income reporting",
    formatLabel: "Platform scenario",
    audienceLabel: "Amazon FBA sellers and third-party marketplace merchants",
    triggerQuestion: "Amazon stores my inventory in warehouses across the country. Does that mean I owe sales tax in all those states?",
    summary: "Amazon FBA creates nexus in every state where your inventory is stored. While Amazon collects and remits sales tax as a marketplace facilitator in most states, FBA sellers still face income tax nexus, inventory tracking, and cost-of-goods-sold complexity.",
    whyThisMatters: "FBA sellers often discover they have filing obligations in dozens of states. Income tax nexus from inventory presence can create multi-state income tax returns, and cost-of-goods-sold tracking directly affects profitability.",
    commonMistake: "Assuming Amazon handles all tax obligations. Amazon collects sales tax as a marketplace facilitator, but it does not file your income tax returns or handle state income tax nexus created by inventory placement.",
    nextMove: "Map where Amazon stores your inventory, understand which states have income tax nexus from physical presence, and implement cost-of-goods-sold tracking that matches your actual Amazon settlement reports.",
    tags: ["Platforms", "Records", "E-commerce"],
    filters: ["platforms", "records"],
    checkpoints: [
      { headline: "Inventory creates physical nexus in those states", detail: "Amazon distributes your inventory across its fulfillment network. Having inventory in a state generally creates physical presence and sales tax or income tax nexus there." },
      { headline: "Marketplace facilitator laws cover sales tax collection", detail: "Amazon collects and remits sales tax in all states with marketplace facilitator laws. But you may still need sales tax registrations for direct sales outside Amazon." },
      { headline: "Income tax nexus is a separate issue", detail: "Even though Amazon handles sales tax, physical inventory presence can create state income tax nexus. Some states may require you to file an income tax return and apportion income." },
      { headline: "Track cost of goods sold accurately", detail: "FBA fees, shipping to Amazon, product costs, and Amazon adjustments all affect COGS. Accurate tracking is necessary for Schedule C or your business return and for inventory-based nexus calculations." },
    ],
    officialLinks: [
      { label: "IRS self-employed tax center", url: "https://www.irs.gov/businesses/small-businesses-self-employed/self-employed-individuals-tax-center" },
      { label: "IRS Schedule C instructions", url: "https://www.irs.gov/forms-pubs/about-schedule-c-form-1040" },
      { label: "Amazon seller tax information", url: "https://sellercentral.amazon.com/help/hub/reference/external/200787660" },
    ],
  },
  {
    id: "rental-income-foreign-owner",
    title: "Foreign owners of U.S. rental property have unique withholding and filing rules",
    formatLabel: "Cross-border scenario",
    audienceLabel: "Non-U.S. persons who own rental real estate in the United States",
    triggerQuestion: "I live outside the U.S. and own a rental property there. What are my U.S. tax obligations on the rental income?",
    summary: "Foreign owners of U.S. rental property face 30% gross withholding by default on rental income. However, making a net income election under IRC Section 871(d) allows you to be taxed on net rental income at graduated rates, which is almost always more favorable.",
    whyThisMatters: "Without the net income election, 30% is withheld on gross rents with no deductions for expenses, mortgage interest, depreciation, or management fees. The election transforms the tax treatment dramatically.",
    commonMistake: "Not making the net income election and accepting the 30% gross withholding, or failing to file the required Form 1040-NR to claim the election and deductions.",
    nextMove: "Make the Section 871(d) election on your first Form 1040-NR, ensure your property manager or tenant is handling withholding correctly, and claim all allowable deductions against rental income.",
    tags: ["Cross-border", "Forms", "Real estate"],
    filters: ["cross-border", "forms"],
    checkpoints: [
      { headline: "Default treatment is 30% withholding on gross rents", detail: "Without an election, FIRPTA and NRA withholding rules require the tenant or property manager to withhold 30% of gross rental payments and remit to the IRS." },
      { headline: "The net income election changes everything", detail: "IRC Section 871(d) lets you elect to treat rental income as effectively connected income, allowing deductions for expenses, depreciation, and mortgage interest against rental revenue." },
      { headline: "Form 1040-NR is required annually", detail: "Foreign rental property owners must file Form 1040-NR to report rental income, claim the net income election, and take allowable deductions. A timely return is essential to preserve the election." },
      { headline: "FIRPTA applies on sale", detail: "When you sell U.S. real property, FIRPTA requires the buyer to withhold 15% of the gross sales price. You recover any excess withholding by filing a Form 1040-NR for the year of sale." },
    ],
    officialLinks: [
      { label: "IRS Publication 519 (U.S. tax guide for aliens)", url: "https://www.irs.gov/publications/p519" },
      { label: "IRS Form 1040-NR", url: "https://www.irs.gov/forms-pubs/about-form-1040-nr" },
      { label: "IRS FIRPTA withholding", url: "https://www.irs.gov/individuals/international-taxpayers/firpta-withholding" },
    ],
  },
  {
    id: "startup-rd-tax-credit",
    title: "Startups can offset payroll taxes with R&D credits",
    formatLabel: "Credit scenario",
    audienceLabel: "Early-stage startups with R&D activity and little or no income tax liability",
    triggerQuestion: "My startup spends heavily on development but has no profit yet. Can the R&D tax credit still help me?",
    summary: "Qualified small businesses (under $5 million in gross receipts, no more than 5 years of gross receipts) can apply up to $500,000 of the R&D credit against their payroll tax liability instead of income tax. This turns the credit into real cash savings even before the company is profitable.",
    whyThisMatters: "Most startups have no income tax liability in their early years, making the traditional R&D credit useless. The payroll tax offset makes the credit immediately valuable during the cash-intensive startup phase.",
    commonMistake: "Assuming the R&D credit only benefits profitable companies, or failing to make the payroll tax election on a timely filed return because the credit was not calculated during the original filing.",
    nextMove: "Identify qualifying R&D activities and expenses, calculate the credit on Form 6765, and elect the payroll tax offset on a timely filed income tax return for the tax year.",
    tags: ["Startups", "Forms", "Year-round"],
    filters: ["forms", "year-round"],
    checkpoints: [
      { headline: "Check the qualified small business criteria", detail: "The company must have gross receipts under $5 million for the credit year and cannot have had gross receipts for any tax year before the 5-tax-year period ending with the credit year." },
      { headline: "Identify qualifying research activities", detail: "The four-part test requires technological uncertainty, a process of experimentation, a technological purpose, and that the research relates to a new or improved business component." },
      { headline: "Calculate the credit on Form 6765", detail: "Use either the regular credit method or the alternative simplified credit method. Most startups use the simplified method. The payroll tax election is made in Section D of Form 6765." },
      { headline: "The election must be on a timely filed return", detail: "The payroll tax offset election cannot be made on an amended return. File your income tax return (or extension) on time and include the completed Form 6765 with the election." },
    ],
    officialLinks: [
      { label: "IRS Form 6765 (R&D credit)", url: "https://www.irs.gov/forms-pubs/about-form-6765" },
      { label: "IRS R&D credit guidance", url: "https://www.irs.gov/businesses/small-businesses-self-employed/research-credit-claims-section-41-irc-audit-techniques-guide" },
      { label: "IRS Notice 2017-23 (payroll tax offset)", url: "https://www.irs.gov/pub/irs-drop/n-17-23.pdf" },
    ],
  },
];
