/* ------------------------------------------------------------------ */
/*  Incorporation Advisor — Structured Country Dataset                */
/* ------------------------------------------------------------------ */

export interface IncorporationCountry {
  countryCode: string;
  country: string;
  corporateRateNumeric: number;
  hasNoPersonalIncomeTax: boolean;
  hasTerritorialTax: boolean;
  vatRate: number;
  easeOfBusiness: number; // 1-10 scale (10 = best)
  startupFriendly: boolean;
  digitalNomadVisa: boolean;
  requiresLocalPresence: boolean;
  treatyNetworkStrength: "strong" | "moderate" | "limited";
  highlights: string[];
  caveats: string[];
}

export const INCORPORATION_COUNTRIES: IncorporationCountry[] = [
  {
    countryCode: "US",
    country: "United States",
    corporateRateNumeric: 21,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 0,
    easeOfBusiness: 9,
    startupFriendly: true,
    digitalNomadVisa: false,
    requiresLocalPresence: false,
    treatyNetworkStrength: "strong",
    highlights: [
      "Largest economy with deep capital markets and investor ecosystem",
      "No VAT/GST at the federal level; state sales tax varies",
      "Delaware and Wyoming LLCs offer strong liability protection and privacy",
    ],
    caveats: [
      "Worldwide taxation for citizens/residents; complex state-level tax obligations",
      "Foreign-owned LLCs face Form 5472 reporting requirements",
      "State income taxes vary widely (0% to 13.3%)",
    ],
  },
  {
    countryCode: "CN",
    country: "China",
    corporateRateNumeric: 25,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 13,
    easeOfBusiness: 5,
    startupFriendly: false,
    digitalNomadVisa: false,
    requiresLocalPresence: true,
    treatyNetworkStrength: "strong",
    highlights: [
      "Massive domestic market with 1.4 billion consumers",
      "15% preferential rate for qualified high-tech enterprises",
      "Special Economic Zones offer additional incentives",
    ],
    caveats: [
      "Complex regulatory environment with capital controls",
      "Foreign investment restrictions in many sectors",
      "Requires local legal representative and registered address",
    ],
  },
  {
    countryCode: "GB",
    country: "United Kingdom",
    corporateRateNumeric: 25,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 20,
    easeOfBusiness: 9,
    startupFriendly: true,
    digitalNomadVisa: false,
    requiresLocalPresence: false,
    treatyNetworkStrength: "strong",
    highlights: [
      "Major financial center with strong rule of law",
      "19% small profits rate for companies under GBP 50K",
      "Extensive R&D tax credits and patent box regime (10% effective rate)",
    ],
    caveats: [
      "25% headline rate for profits above GBP 250K",
      "20% VAT adds cost for B2C businesses",
      "IR35 rules complicate contractor arrangements",
    ],
  },
  {
    countryCode: "DE",
    country: "Germany",
    corporateRateNumeric: 30,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 19,
    easeOfBusiness: 8,
    startupFriendly: false,
    digitalNomadVisa: false,
    requiresLocalPresence: true,
    treatyNetworkStrength: "strong",
    highlights: [
      "Europe's largest economy with strong industrial base",
      "Extensive double tax treaty network (90+ countries)",
      "EU membership provides access to single market",
    ],
    caveats: [
      "Effective corporate rate ~30% including trade tax (Gewerbesteuer)",
      "Complex bureaucratic requirements for company formation",
      "High social security contributions for employers",
    ],
  },
  {
    countryCode: "FR",
    country: "France",
    corporateRateNumeric: 25,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 20,
    easeOfBusiness: 7,
    startupFriendly: true,
    digitalNomadVisa: false,
    requiresLocalPresence: true,
    treatyNetworkStrength: "strong",
    highlights: [
      "French Tech Visa program attracts tech entrepreneurs",
      "R&D tax credit (CIR) covers up to 30% of qualifying expenditures",
      "EU single market access with strong IP protection",
    ],
    caveats: [
      "High employer social charges (~45% on top of salary)",
      "Complex labor laws make hiring/firing difficult",
      "Wealth tax on real estate assets above EUR 1.3M",
    ],
  },
  {
    countryCode: "JP",
    country: "Japan",
    corporateRateNumeric: 30,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 10,
    easeOfBusiness: 7,
    startupFriendly: false,
    digitalNomadVisa: true,
    requiresLocalPresence: true,
    treatyNetworkStrength: "strong",
    highlights: [
      "Third-largest economy with sophisticated consumer market",
      "Strong IP protection and technology infrastructure",
      "Digital nomad visa launched for remote workers",
    ],
    caveats: [
      "Effective corporate rate ~30% including local taxes",
      "Japanese language requirements for most business dealings",
      "Complex immigration requirements for business visas",
    ],
  },
  {
    countryCode: "KR",
    country: "South Korea",
    corporateRateNumeric: 24,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 10,
    easeOfBusiness: 8,
    startupFriendly: true,
    digitalNomadVisa: true,
    requiresLocalPresence: true,
    treatyNetworkStrength: "strong",
    highlights: [
      "Tech-forward economy with excellent digital infrastructure",
      "Startup-friendly policies and government grants for innovation",
      "Digital nomad visa (Workcation visa) available",
    ],
    caveats: [
      "Top marginal corporate rate of 24% for large profits",
      "Korean language dominates business environment",
      "Complex regulations for foreign-owned companies",
    ],
  },
  {
    countryCode: "IN",
    country: "India",
    corporateRateNumeric: 25,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 18,
    easeOfBusiness: 6,
    startupFriendly: true,
    digitalNomadVisa: false,
    requiresLocalPresence: true,
    treatyNetworkStrength: "strong",
    highlights: [
      "New manufacturing companies can opt for 15% rate",
      "Large English-speaking talent pool at competitive costs",
      "Startup India initiative offers 3-year tax holiday for eligible startups",
    ],
    caveats: [
      "Complex GST system with multiple rate slabs (5%, 12%, 18%, 28%)",
      "Bureaucratic company registration process",
      "Angel tax and transfer pricing scrutiny for foreign investors",
    ],
  },
  {
    countryCode: "BR",
    country: "Brazil",
    corporateRateNumeric: 34,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 17,
    easeOfBusiness: 4,
    startupFriendly: false,
    digitalNomadVisa: true,
    requiresLocalPresence: true,
    treatyNetworkStrength: "limited",
    highlights: [
      "Largest economy in Latin America with 210M+ population",
      "Digital nomad visa available for remote workers",
      "Simples Nacional regime offers simplified tax for small businesses",
    ],
    caveats: [
      "One of the most complex tax systems globally (34% effective rate)",
      "Limited treaty network increases double taxation risk",
      "Extensive bureaucracy for company formation and compliance",
    ],
  },
  {
    countryCode: "CA",
    country: "Canada",
    corporateRateNumeric: 26.5,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 5,
    easeOfBusiness: 9,
    startupFriendly: true,
    digitalNomadVisa: false,
    requiresLocalPresence: false,
    treatyNetworkStrength: "strong",
    highlights: [
      "Small business deduction lowers rate to ~12.2% on first CAD 500K",
      "SR&ED tax credit program is one of the most generous R&D incentives globally",
      "Stable legal system with proximity to U.S. market",
    ],
    caveats: [
      "Combined federal-provincial rate can reach 26.5%+",
      "Provincial taxes vary significantly across jurisdictions",
      "GST/HST system adds compliance complexity",
    ],
  },
  {
    countryCode: "AU",
    country: "Australia",
    corporateRateNumeric: 30,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 10,
    easeOfBusiness: 8,
    startupFriendly: true,
    digitalNomadVisa: false,
    requiresLocalPresence: false,
    treatyNetworkStrength: "strong",
    highlights: [
      "25% rate for base rate entities (turnover < AUD 50M)",
      "R&D tax incentive offers 43.5% refundable offset for small companies",
      "Strong rule of law and transparent regulatory environment",
    ],
    caveats: [
      "30% headline rate for large companies",
      "10% GST applies to most goods and services",
      "Strict anti-avoidance rules and transfer pricing enforcement",
    ],
  },
  {
    countryCode: "SG",
    country: "Singapore",
    corporateRateNumeric: 17,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: true,
    vatRate: 9,
    easeOfBusiness: 10,
    startupFriendly: true,
    digitalNomadVisa: false,
    requiresLocalPresence: true,
    treatyNetworkStrength: "strong",
    highlights: [
      "17% headline rate with effective rate as low as 8.5% for new startups",
      "Territorial tax system -- foreign-sourced income generally not taxed unless remitted",
      "No capital gains tax; no tax on dividends to shareholders",
    ],
    caveats: [
      "Requires at least one local resident director",
      "9% GST increased from 8% in 2024",
      "Cost of living and office space among the highest globally",
    ],
  },
  {
    countryCode: "HK",
    country: "Hong Kong",
    corporateRateNumeric: 16.5,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: true,
    vatRate: 0,
    easeOfBusiness: 9,
    startupFriendly: true,
    digitalNomadVisa: false,
    requiresLocalPresence: true,
    treatyNetworkStrength: "moderate",
    highlights: [
      "8.25% on first HKD 2M of profits; 16.5% thereafter",
      "Strict territorial taxation -- only HK-sourced income is taxed",
      "No VAT/GST, no capital gains tax, no withholding tax on dividends",
    ],
    caveats: [
      "Requires local company secretary and registered address",
      "Smaller treaty network than Singapore (~45 treaties)",
      "New foreign-sourced income exemption regime tightened rules in 2023",
    ],
  },
  {
    countryCode: "AE",
    country: "United Arab Emirates",
    corporateRateNumeric: 9,
    hasNoPersonalIncomeTax: true,
    hasTerritorialTax: true,
    vatRate: 5,
    easeOfBusiness: 8,
    startupFriendly: true,
    digitalNomadVisa: true,
    requiresLocalPresence: true,
    treatyNetworkStrength: "moderate",
    highlights: [
      "9% corporate tax with 0% on first AED 375K; free zone companies may qualify for 0%",
      "Zero personal income tax on salary, dividends, and capital gains",
      "Digital nomad / remote work visa programs in Dubai and Abu Dhabi",
    ],
    caveats: [
      "Corporate tax introduced in 2023 -- still evolving regulations",
      "Free zone benefits require meeting economic substance requirements",
      "5% VAT applies to most goods and services",
    ],
  },
  {
    countryCode: "IE",
    country: "Ireland",
    corporateRateNumeric: 15,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 23,
    easeOfBusiness: 9,
    startupFriendly: true,
    digitalNomadVisa: false,
    requiresLocalPresence: true,
    treatyNetworkStrength: "strong",
    highlights: [
      "12.5% rate for trading income (15% for companies in scope of Pillar Two)",
      "Knowledge Development Box offers 6.25% effective rate on qualifying IP income",
      "EU membership and English-speaking -- major tech hub (Google, Apple, Meta HQs)",
    ],
    caveats: [
      "23% VAT rate is one of the highest in the EU",
      "High personal income tax rates (up to 52% marginal)",
      "Must have at least one EU/EEA-resident director",
    ],
  },
  {
    countryCode: "NL",
    country: "Netherlands",
    corporateRateNumeric: 25.8,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 21,
    easeOfBusiness: 8,
    startupFriendly: true,
    digitalNomadVisa: false,
    requiresLocalPresence: true,
    treatyNetworkStrength: "strong",
    highlights: [
      "19% rate on first EUR 200K of profits; innovation box offers 9% on qualifying IP",
      "Participation exemption eliminates tax on qualifying dividends and capital gains",
      "One of the largest treaty networks globally (100+ treaties)",
    ],
    caveats: [
      "25.8% standard rate above EUR 200K threshold",
      "21% VAT rate; complex employment tax obligations",
      "Increasing scrutiny on holding company structures (anti-abuse rules)",
    ],
  },
  {
    countryCode: "CH",
    country: "Switzerland",
    corporateRateNumeric: 14.9,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 8.1,
    easeOfBusiness: 9,
    startupFriendly: true,
    digitalNomadVisa: false,
    requiresLocalPresence: true,
    treatyNetworkStrength: "strong",
    highlights: [
      "Effective combined federal/cantonal rate ranges from 11.9% to 21.6% by canton",
      "Patent box regime and R&D super deduction lower effective rates further",
      "Political stability, strong IP protection, and robust banking system",
    ],
    caveats: [
      "Rates vary significantly by canton -- Zug (~11.9%) vs. Geneva (~14%)",
      "High cost of living and labor costs",
      "Work permits for non-EU/EFTA nationals are strictly limited",
    ],
  },
  {
    countryCode: "MX",
    country: "Mexico",
    corporateRateNumeric: 30,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 16,
    easeOfBusiness: 5,
    startupFriendly: false,
    digitalNomadVisa: false,
    requiresLocalPresence: true,
    treatyNetworkStrength: "moderate",
    highlights: [
      "USMCA trade agreement provides duty-free access to US and Canada",
      "Competitive labor costs and growing nearshoring trend",
      "Maquiladora/IMMEX program offers tax benefits for manufacturing",
    ],
    caveats: [
      "30% flat corporate tax rate with limited incentives",
      "Complex transfer pricing rules and anti-avoidance measures",
      "Profit sharing (PTU) requires distributing 10% of pre-tax profits to employees",
    ],
  },
  {
    countryCode: "ID",
    country: "Indonesia",
    corporateRateNumeric: 22,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 11,
    easeOfBusiness: 5,
    startupFriendly: false,
    digitalNomadVisa: true,
    requiresLocalPresence: true,
    treatyNetworkStrength: "moderate",
    highlights: [
      "Large domestic market (270M+ population) with growing middle class",
      "50% tax discount for SMEs with turnover under IDR 50B (effective 11% rate)",
      "Digital nomad visa (Second Home Visa) available for remote workers",
    ],
    caveats: [
      "Foreign ownership restrictions in many sectors (Negative Investment List)",
      "Complex bureaucratic environment for foreign companies",
      "11% VAT increasing to 12% under new regulations",
    ],
  },
  {
    countryCode: "EE",
    country: "Estonia",
    corporateRateNumeric: 20,
    hasNoPersonalIncomeTax: false,
    hasTerritorialTax: false,
    vatRate: 22,
    easeOfBusiness: 9,
    startupFriendly: true,
    digitalNomadVisa: true,
    requiresLocalPresence: false,
    treatyNetworkStrength: "moderate",
    highlights: [
      "0% corporate tax on retained/reinvested profits -- only taxed on distribution (20%)",
      "e-Residency program allows fully digital company setup from anywhere",
      "Digital nomad visa and EU single market access",
    ],
    caveats: [
      "20% tax applies when profits are distributed as dividends",
      "22% VAT rate is relatively high",
      "Small domestic market (1.3M population) -- primarily a gateway to EU",
    ],
  },
];
