// AUTO-GENERATED by scripts/cross-project-drip.ts — do NOT edit by hand.
//
// Daily cron pulls items from the cross-project router feed at
// https://foreignllctax.com/tax-news-router-output.json — items the
// foreignllctax.com pipeline classified as "tax-relevant but not
// foreign-LLC-specific". This script AI-generates commentary for the
// tax-guided audience and appends entries between the AUTO-CONTENT markers
// below.
//
// Manual edits between the markers will be lost on the next cron run.
//
// Kill switch: set repo variable CROSS_PROJECT_DRIP_DISABLED=true.
// See CLAUDE.md "Cross-project router consumer" section for full architecture.

import type { NewsCommentaryItem } from "./news-commentary";

export const AUTO_NEWS_COMMENTARY: NewsCommentaryItem[] = [
  // ==== AUTO-CONTENT START ====
  // ==== AUTO-CONTENT END ====
];
